import Reveal from '../components/Reveal'

const FEEDBACK_EMAIL = 'info@bytecrisp.com'

const SECTIONS = [
  {
    heading: 'The short version',
    paragraphs: [
      'The calculations you run stay on your phone. You can use every tool without an account; signing in with Google is optional, and all it stores is your email address.',
    ],
  },
  {
    heading: 'What we store on your device',
    paragraphs: ['My Life Kit saves a small amount of data locally so the app feels like yours:'],
    bullets: [
      'Which tools you marked as favorites.',
      'Which tools you opened recently — the tool name only, never what you typed into it.',
      'Your preferences: theme, language and haptic feedback.',
      'A cached copy of exchange rates, if live rates have been enabled.',
    ],
  },
  {
    heading: 'What we never collect',
    paragraphs: ['My Life Kit does not ask for, transmit or store any of the following:'],
    bullets: [
      'Your name, phone number, or any password. (If you sign in, we store your email address — see below. If you do not, we store nothing about you at all.)',
      'The amounts, dates, passwords or text you enter into any tool.',
      'Passwords generated by the Password Generator — they exist only on screen.',
      'The contents of QR codes you scan or create.',
      'Your photos. Images picked for a PDF are read and converted on the device.',
      'Your location.',
    ],
  },
  {
    heading: 'If you sign in',
    paragraphs: [
      'Signing in with Google is entirely optional — "Continue as Guest" on the welcome screen skips it, and every tool works the same either way. An account exists so that a paid plan follows you to a new phone instead of dying with the old one.',
      'If you do sign in, Google tells us your email address and we create one row in our database holding:',
    ],
    bullets: [
      'Your email address.',
      'An account identifier generated by our authentication provider.',
      'A notification token, if you have allowed notifications, so we can reach that device.',
      'The dates the row was created and last changed.',
    ],
  },
  {
    heading: 'What signing in does not change',
    paragraphs: [
      'Nothing you type into a tool is uploaded, whether you are signed in or not. Amounts, dates, passwords, scanned codes and photos are handled on the device exactly as described above. An account records who you are for billing; it does not record what you do in the app.',
      'You can sign out at any time from Settings → Account, which returns the app to guest mode. To have the account and its row deleted outright, email us and we will remove it.',
    ],
  },
  {
    heading: 'Permissions',
    paragraphs: [
      'My Life Kit asks for a permission only at the moment a tool needs it, and explains why first.',
    ],
    bullets: [
      'Camera — requested when you open the QR Scanner, used only to read codes in the live preview. Nothing is recorded.',
      'Photos — requested when you use Image to PDF, so you can choose which pictures to include.',
      'Storage / media — requested only when you choose to save a QR image or a PDF.',
      'Notifications — requested only after you sign in, so we can tell you about your account and plan. Declining changes nothing else about the app.',
    ],
  },
  {
    heading: 'Network use',
    paragraphs: [
      'Nearly every tool works fully offline, and the app makes no network request at all while you are using one. Three things can reach the internet:',
    ],
    bullets: [
      'Prices — the Currency Converter and the gold and crypto screens read a public table of rates. Nothing about you is sent with that request, and if it fails the app falls back to a snapshot bundled with the app, clearly labelled as not live.',
      'Signing in — only when you tap the Google button, and only to exchange your Google sign-in for a session.',
      'Notifications — if you have allowed them, the device registers a push token so we can reach it. Nothing else is sent.',
    ],
  },
  {
    heading: 'Advertising',
    paragraphs: [
      "This build of My Life Kit ships with advertising turned off. If a future release enables Google AdMob, ads may use a device advertising identifier under Google's own privacy policy, and this section will be updated to say so before that release goes out. Ads never see the content of your calculations.",
    ],
  },
  {
    heading: 'Children',
    paragraphs: [
      'My Life Kit is a general-purpose utility. It does not knowingly collect information from anyone, including children, because it does not collect personal information at all.',
    ],
  },
  {
    heading: 'Deleting your data',
    paragraphs: [
      'Because everything lives on your device, you are always in control. Settings → Reset app data clears your favorites, recent tools and preferences immediately. Uninstalling My Life Kit removes everything it ever stored.',
    ],
  },
  {
    heading: 'Changes to this policy',
    paragraphs: [
      'If this policy changes in a way that affects you, the updated version will ship with a new release of the app and the date above will change.',
    ],
  },
]

function MyLifeKitPrivacyPolicy() {
  return (
    <section className="page-section my-life-kit-page">
      <Reveal className="page-intro">
        <span className="eyebrow">My Life Kit</span>
        <h1>Privacy Policy</h1>
        <p>
          My Life Kit is built so that there is almost nothing to have a privacy policy about. This page explains
          exactly what the app does and does not do with your information.
        </p>
        <p>Last updated: January 2025</p>
      </Reveal>

      {SECTIONS.map((section, index) => (
        <Reveal as="div" className="story-panel" delay={60 + index * 30} key={section.heading}>
          <h2>{section.heading}</h2>
          {section.paragraphs.map((paragraph) => (
            <p key={paragraph}>{paragraph}</p>
          ))}
          {section.bullets && (
            <ul className="values-list">
              {section.bullets.map((bullet) => (
                <li key={bullet}>{bullet}</li>
              ))}
            </ul>
          )}
        </Reveal>
      ))}

      <Reveal as="div" className="story-panel" delay={60 + SECTIONS.length * 30}>
        <h2>Contact</h2>
        <p>
          Questions about privacy? Write to{' '}
          <a href={`mailto:${FEEDBACK_EMAIL}`}>{FEEDBACK_EMAIL}</a>.
        </p>
      </Reveal>
    </section>
  )
}

export default MyLifeKitPrivacyPolicy
